oce_regions = [
"APAC - WM153002",
"EMEA - WM153003",
"JAPAN - WM153004",
"LAD - WM153005",
"NA - WM153006",
"WORLDWIDE - WM153007"
]
oce_countries = [
"Mozambique - WM170741",
"Myanmar - WM170728",
"Namibia - WM170742",
"Nauru - WM170751",
"Nepal - WM170750",
"Netherlands - WM170748",
"New Caledonia - WM170743",
"New Zealand - WM170753",
"Nicaragua - WM170747",
"Niger - WM170744",
"Nigeria - WM170746",
"Niue - WM170752",
"Norfolk Island - WM170745",
"Northern Mariana Islands - WM170731",
"Norway - WM170749",
"Oman - WM170754",
"Pakistan - WM170760",
"Palau - WM170767",
"Palestine - WM170765",
"Panama - WM170755",
"Papua New Guinea - WM170758",
"Paraguay - WM170768",
"Peru - WM170756",
"Philippines - WM170759",
"Pitcairn - WM170763",
"Poland - WM170761",
"Portugal - WM170766",
"Puerto Rico - WM170764",
"Qatar - WM170769",
"Romania - WM170771",
"Russian Federation - WM170773",
"Rwanda - WM170774",
"Réunion - WM170770",
"Saint Barthélemy - WM170607",
"Saint Helena - WM170781",
"Saint Kitts and Nevis - WM170702",
"Saint Lucia - WM170710",
"Saint Martin, French - WM170723",
"Saint Pierre and Miquelon - WM170762",
"Saint Vincent and the Grenadines - WM170819",
"Samoa - WM170826",
"San Marino - WM170786",
"Sao Tome and Principe - WM170791",
"Saudi Arabia - WM170775",
"Senegal - WM170787",
"Serbia - WM170772",
"Seychelles - WM170777",
"Sierra Leone - WM170785",
"Singapore - WM170780",
"Sint Maarten, Dutch - WM170793",
"Slovakia - WM170784",
"Slovenia - WM170782",
"Solomon Islands - WM170776",
"Somalia - WM170788",
"South Africa - WM170829",
"South Georgia and the South Sandwich Islands - WM170672",
"South Sudan - WM170790",
"Spain - WM170650",
"Sri Lanka - WM170712",
"Sudan - WM170778",
"Suriname - WM170789",
"Svalbard and Jan Mayen - WM170783",
"Swaziland - WM170795",
"Sweden - WM170779",
"Switzerland - WM170625",
"Syrian Arab Republic - WM170794",
"Taiwan - WM170810",
"Tajikistan - WM170801",
"Tanzania - WM170811",
"Thailand - WM170800",
"Timor-Leste - WM170803",
"Togo - WM170799",
"Tokelau - WM170802",
"Tonga - WM170806",
"Trinidad and Tobago - WM170808",
"Tunisia - WM170805",
"Turkey - WM170807",
"Turkmenistan - WM170804",
"Turks and Caicos Islands - WM170796",
"Tuvalu - WM170809",
"Uganda - WM170813",
"Ukraine - WM170812",
"United Arab Emirates - WM170583",
"United Kingdom - WM170659",
"United States - WM170815",
"United States Minor Outlying Islands - WM170814",
"Uruguay - WM170816",
"Uzbekistan - WM170817",
"Vanuatu - WM170824",
"Vatican City, Holy See - WM170818",
"Venezuela - WM170820",
"Viet Nam - WM170823",
"Virgin Islands, British - WM170821",
"Virgin Islands, U.S. - WM170822",
"Wallis and Futuna - WM170825",
"Western Sahara - WM170648",
"Yemen - WM170827",
"Zambia - WM170830",
"Zimbabwe - WM170831",
"Åland Islands - WM170596",
"Afghanistan - WM170584",
"Albania - WM170587",
"Algeria - WM170644",
"American Samoa - WM170592",
"Andorra - WM170975",
"Angola - WM170589",
"Anguilla - WM170586",
"Antarctica - WM170590",
"Antigua and Barbuda - WM170585",
"Argentina - WM170591",
"Armenia - WM170588",
"Aruba - WM170595",
"Australia - WM170594",
"Austria - WM170593",
"Azerbaijan - WM170597",
"Bahamas - WM170614",
"Bahrain - WM170604",
"Bangladesh - WM170600",
"Barbados - WM170599",
"Belarus - WM170618",
"Belgium - WM170601",
"Belize - WM170619",
"Benin - WM170606",
"Bermuda - WM170608",
"Bhutan - WM170615",
"Bolivia - WM170610",
"Bonaire, Sint Eustatius and Saba - WM170612",
"Bosnia and Herzegovina - WM170598",
"Botswana - WM170617",
"Bouvet Island - WM170616",
"Brazil - WM170613",
"British Indian Ocean Territory - WM170688",
"Brunei Darussalam - WM170609",
"Bulgaria - WM170603",
"Burkina Faso - WM170602",
"Burundi - WM170605",
"Cabo Verde - WM170634",
"Cambodia - WM170699",
"Cameroon - WM170629",
"Canada - WM170620",
"Cayman Islands - WM170706",
"Central African Republic - WM170623",
"Chad - WM170797",
"Chile - WM170628",
"China - WM170630",
"Christmas Island - WM170636",
"Cocos (Keeling) Islands - WM170621",
"Colombia - WM170631",
"Comoros - WM170701",
"Congo, Democratic Republic of the Congo - WM170622",
"Congo, Republic of the Congo - WM170624",
"Cook Islands - WM170627",
"Costa Rica - WM170632",
"Croatia - WM170680",
"Cuba - WM170633",
"Curaçao - WM170635",
"Cyprus - WM170637",
"Czech Republic - WM170638",
"Côte d'Ivoire - WM170626",
"Denmark - WM170641",
"Djibouti - WM170640",
"Dominica - WM170642",
"Dominican Republic - WM170643",
"Ecuador - WM170645",
"Egypt - WM170647",
"El Salvador - WM170792",
"Equatorial Guinea - WM170670",
"Eritrea - WM170649",
"Estonia - WM170646",
"Ethiopia - WM170651",
"Falkland Islands, Islas Malvinas - WM170654",
"Faroe Islands - WM170656",
"Fiji - WM170653",
"Finland - WM170652",
"France - WM170657",
"French Guiana - WM170662",
"French Polynesia - WM170757",
"French Southern Territories - WM170798",
"Gabon - WM170658",
"Gambia - WM170667",
"Georgia - WM170661",
"Germany - WM170639",
"Ghana - WM170664",
"Gibraltar - WM170665",
"Greece - WM170671",
"Greenland - WM170666",
"Grenada - WM170660",
"Guadeloupe - WM170669",
"Guam - WM170674",
"Guatemala - WM170673",
"Guernsey - WM170663",
"Guinea - WM170668",
"Guinea-Bissau - WM170675",
"Guyana - WM170676",
"Haiti - WM170681",
"Heard Island and McDonald Islands - WM170678",
"Honduras - WM170679",
"Hong Kong SAR, PRC - WM170677",
"Hungary - WM170682",
"Iceland - WM170691",
"Slovenia - WM170782",
"Solomon Islands - WM170776",
"Somalia - WM170788",
"South Africa - WM170829",
"South Georgia and the South Sandwich Islands - WM170672",
"South Sudan - WM170790",
"Spain - WM170650",
"Sri Lanka - WM170712",
"Sudan - WM170778",
"Suriname - WM170789",
"Svalbard and Jan Mayen - WM170783",
"Swaziland - WM170795",
"Sweden - WM170779",
"Switzerland - WM170625",
"Syrian Arab Republic - WM170794",
"Taiwan - WM170810",
"Tajikistan - WM170801",
"Tanzania - WM170811",
"Thailand - WM170800",
"Timor-Leste - WM170803",
"Togo - WM170799",
"Tokelau - WM170802",
"Tonga - WM170806",
"Trinidad and Tobago - WM170808",
"Tunisia - WM170805",
"Turkey - WM170807",
"Turkmenistan - WM170804",
"Turks and Caicos Islands - WM170796",
"Tuvalu - WM170809",
"Uganda - WM170813",
"Ukraine - WM170812",
"United Arab Emirates - WM170583",
"United Kingdom - WM170659",
"United States - WM170815",
"United States Minor Outlying Islands - WM170814",
"Uruguay - WM170816",
"Uzbekistan - WM170817",
"Vanuatu - WM170824",
"Vatican City, Holy See - WM170818",
"Venezuela - WM170820",
"Viet Nam - WM170823",
"Virgin Islands, British - WM170821",
"Virgin Islands, U.S. - WM170822",
"Wallis and Futuna - WM170825",
"Western Sahara - WM170648",
"Yemen - WM170827",
"Zambia - WM170830",
"Zimbabwe - WM170831",
"Åland Islands - WM170596"
]
oce_industries = [
"Manufacturing - WM172877",
"Media and Entertainment - WM148055",
"Natural Resources - WM148056",
"Oil and Gas - WM148057",
"Primary and Secondary Education (K-12) - WM178656",
"Professional Services - WM148058",
"Public Sector - WM148059",
"Research Organizations - WM178655",
"Retail - WM148060",
"Aerospace and Defense - WM148042",
"Automotive - WM148043",
"Chemicals - WM148044",
"Communications - WM148045",
"Consumer Goods - WM148046",
"Education and Research - WM148047",
"Construction and Engineering - WM148048",
"Financial Services - WM148049",
"Financial Services Banking - WM178657",
"Financial Services Capital Markets - WM178658",
"Food and Beverage - WM179499",
"Health Sciences - WM178659",
"Healthcare - WM148050",
"High Technology - WM148051",
"Higher Education - WM178654",
"Hospitality - WM175551",
"Industrial Manufacturing - WM148052",
"Insurance - WM148053",
"Life Sciences - WM148054",
"Travel and Transportation - WM148061",
"Utilities - WM148062",
"Wholesale Distribution - WM148063"
]
products_name = {
"Planning",
"Construction and Engineering",
"Innovation Lab",
"Payment Management",
"Primary and Secondary Education",
"Communications",
"Enterprise Communications",
"Service Provider Network",
"Service Provider Applications",
"Advertising (Data Cloud)",
"Measurement",
"Moat Reach",
"Moat Analytics",
"Project Controls and Collaboration",
"Asset Lifecycle Management",
"Schedule, Portfolio, and Risk Management",
"Food and Beverage",
"POS Integrations",
"POS Hardware",
"Restaurant POS Systems",
"Sports & Entertainment Solutions",
"Financial Services",
"Insurance",
"Corporate Banking",
"Retail Banking",
"Modern Risk and Finance",
"Financial Crime and Compliance Management",
"Education",
"Research",
"Higher Education",
"Moat Outcomes",
"Activation",
"OnRamp",
"Audiences",
"Contextual Intelligence",
"On-Premises Applications",
"Hyperion",
"PeopleSoft",
"Siebel",
"JD Edwards",
"E-Business Suite",
"Oracle Cloud Infrastructure",
"Database Services",
"Standard Database Service",
"MySQL Database Service",
"Enterprise Database Service",
"NoSQL Database Service",
"Exadata Database Service",
"OCI Solutions",
"High Performance Computing Solutions",
"Oracle Azure Cross-Cloud Interconnect",
"Oracle Cloud VMware Solution",
"Oracle Cloud Marketplace Partners",
"Database Management Tools",
"GoldenGate",
"Data Integration",
"Data Integrator (ODI)",
"Application Development",
"Content and Experience (OCE)",
"Blockchain",
"Blockchain Platform",
"Java SE",
"GraalVM",
"WebLogic",
"DevOps",
"Cloud Shell",
"Notifications",
"Visual Builder Studio",
"Resource Manager",
"Logging Analytics",
"Logging",
"Email Delivery",
"Monitoring",
"Visual Builder",
"APEX - Application Express",
"Cloud Native",
"Events Service",
"Functions (serverless)",
"Streaming",
"Container Registry (OCIR)",
"Container Engine for Kubernetes (OKE)",
"API Management",
"Machine Learning and AI",
"OCI Data Science",
"In-database Machine Learning",
"Oracle Cloud Infrastructure Data Science",
"Virtual Machines for Data Science",
"Oracle AI Services",
"Oracle Digital Assistant",
"OCI Vision",
"OCI Language",
"OCI Speech",
"OCI Anomaly Detection",
"Integration",
"API Management",
"Data Integration",
"GoldenGate",
"Data Integrator",
"Data Integration",
"Application Integration",
"Integration",
"Service-Oriented Architecture (SOA)",
"Networking",
"Virtual Cloud Networks",
"Health Checks",
"FastConnect",
"VPN Connect",
"Traffic Management",
"Service Gateway",
"DNS",
"Load Balancing",
"Security, Identity, and Compliance",
"Web Application Firewall",
"Identity and Access Management",
"Vault",
"Security Zones",
"CASB Cloud Service",
"Data Safe",
"Identity Cloud Service",
"Cloud Guard",
"Analytics",
"Analytics Cloud",
"Fusion Analytics",
"Fusion ERP Analytics",
"Fusion HCM Analytics",
"Fusion SCM Analytics",
"Cloud@Customer",
"Dedicated Region Cloud@Customer",
"Exadata Database Cloud@Customer",
"Compute",
"OS Management Service",
"Autonomous Linux",
"Compute Instances",
"Virtual Machines",
"Bare Metal",
"Virtual Machines and Bare Metal (GPU)",
"Functions",
"Big Data",
"Spark Service",
"Big Data Service",
"Cloud SQL",
"Data Catalog",
"Observability and Management",
"Service Connector Hub",
"Application Performance  Monitoring",
"Operations Insights",
"Resource Manager (Terraform)",
"Monitoring",
"Logging Analytics",
"Logging",
"Storage",
"Data Transfer Appliance",
"Object Storage",
"File Storage",
"Block Storage",
"Archive Storage",
"Storage Gateway",
"Autonomous Database",
"Autonomous JSON Database",
"Autonomous Data Warehouse (ADW)",
"Autonomous Transaction Processing (ATP)",
"On-Premises Infrastructure",
"Application Development Software",
"GraalVM",
"WebCenter Suite",
"WebCenter Portal",
"WebCenter Content",
"WebCenter Sites",
"Coherence",
"WebLogic Server",
"Java SE",
"Servers and Storage",
"ZFS Storage Appliance",
"StorageTek Tape Libraries",
"X86 Servers",
"SPARC Servers",
"Database Software",
"Database Enterprise Edition",
"MySQL Database",
"NoSQL Database",
"TimesTen",
"Database Standard Edition",
"Security Software",
"Database Security Software",
"Audit Vault and Database Firewall",
"Advanced Security",
"Data Masking and Subsetting",
"Label Security",
"Key Vault",
"Database Vault",
"Database Security Assessment Tool",
"Identity & Access Management Software",
"Directory Services",
"Identity Governance",
"Access Management",
"Engineered Systems",
"Database Appliance",
"Private Cloud Appliance",
"Zero Data Loss Recovery Appliance",
"Exadata Database Machine",
"Integration",
"Service-Oriented Architecture (SOA)",
"Data Integration",
"Data Integrator",
"GoldenGate",
"Analytics Software",
"Essbase",
"Analytics Server",
"Infrastructure Software",
"Solaris",
"Linux",
"Virtualization",
"VM Virtual Box",
"Enterprise Manager Software",
"Enterprise Manager",
"Oracle Cloud Applications",
"NetSuite Applications",
"Professional Services Automation",
"Human Resources",
"Customer Relationship Management",
"Financials & ERP",
"Commerce",
"Fusion Applications Suite",
"Supply Chain & Manufacturing (SCM)",
"Order Management",
"Service Contracts",
"Order Management",
"Logistics",
"Transportation Operational Planning",
"Transportation Management",
"Fleet Management",
"Warehouse Management",
"Logistics Network Modeling",
"Global Trade Management",
"Procurement",
"Self-Service Procurement",
"Procurement",
"Inventory Management",
"Blockchain",
"Intelligent Track and Trace",
"Maintenance",
"Manufacturing",
"Supply Chain Planning",
"Sales and Operations Planning",
"Supply Chain Collaboration",
"Demand Management",
"Supply Planning",
"Product Lifecycle Management",
"Internet of Things (IoT)",
"Mobile Worker for IoT Intelligent Applications",
"IoT 3D Digital Twin",
"IoT Intelligent Applications",
"Marketing",
"B2C Marketing",
"CrowdTwist Loyalty and Engagement",
"Audience Segmentation",
"Infinity Behavioral Intelligence",
"BlueKai Data Management Platform",
"Unity Customer Data Platform",
"Maxymiser Testing and Optimization",
"Content Management",
"Responsys Campaign Management",
"B2B Marketing",
"DataFox Data Management",
"Maxymiser Testing and Optimization",
"CrowdTwist Loyalty and Engagement",
"Infinity Behavioral Intelligence",
"Eloqua Marketing Automation",
"Content Management",
"Unity Customer Data Platform",
"Human Capital Management (HCM)",
"HCM Analytics",
"Workforce Management",
"Absence Management",
"Workforce Health and Safety",
"Time and Labor",
"Human Resources",
"Benefits",
"Human Resources (Core)",
"Work Life",
"Human Resources Help Desk",
"Strategic Workforce Planning",
"Advanced HCM Controls",
"Workforce Modeling and Predictions",
"Payroll",
"United States Payroll",
"Canada Payroll",
"Mexico Payroll",
"Middle East Payroll",
"China Payroll",
"United Kingdom Payroll",
"Talent Management",
"Learning",
"Onboarding",
"Compensation",
"Succession Planning",
"Recruiting",
"Performance Management",
"Enterprise Resource Planning (ERP)",
"Procurement",
"Procurement",
"Self-Service Procurement",
"ERP Analytics",
"Financial Management",
"Subscription Management",
"Accounting Hub",
"Financials",
"Self-Service Financials",
"Configure, Price, Quote",
"Risk Management and Compliance",
"Financial Reporting Compliance",
"Risk Management",
"Project Management",
"Project Management",
"Self-Service Project Management",
"Enterprise Performance Management",
"Enterprise Performance Management",
"Enterprise Data Management",
"Sales",
"Commerce",
"B2C Commerce",
"B2B Commerce",
"Configure, Price, Quote",
"Subscription Management",
"Sales Automation",
"Customer Data Management",
"Sales Performance Management",
"Sales Planning",
"DataFox Data Management",
"Sales Force Automation",
"Partner Relationship Management",
"Service",
"Field Service",
"B2B Service",
"Service Center",
"Digital Customer Service",
"Knowledge Management",
"Intelligent Advisor",
"B2C Service",
"Digital Customer Service",
"Intelligent Advisor",
"Service Center",
"Knowledge Management",
"Industry-Specific Applications",
"Hospitality",
"Cruise",
"Casinos and Gaming",
"Hotels and Resorts",
"Utilities",
"Customer Operations and Engagement",
"Asset and Field Work Management",
"Advanced Metering",
"Network Management",
"Opower",
"Live Energy Connect",
"Life Sciences",
"Pharmacovigilance",
"Clinical Research",
"Retail",
"Omnichannel",
"Hardware",
"Merchandising",
"Insights and Science",
"Supply Chain",
"Brand Compliance Management"
}
l3_products = {
"Enterprise Performance Management",
"Supply Chain Planning",
"Supply Chain Planning",
"Supply Chain Planning",
"Supply Chain Planning",
"Order Management",
"Order Management",
"Procurement",
"Procurement",
"Logistics",














"Logistics",
"Logistics",
"Logistics",
"Logistics",
"Logistics",
"Blockchain",
"Blockchain",
"Internet of Things (IoT)",
"Internet of Things (IoT)",

"Fusion ERP Analytics",






"Internet of Things (IoT)",
"Human Resources",
"Human Resources",
"Human Resources",
"Human Resources",
"Human Resources",
"Human Resources",
"Fusion HCM Analytics",
"Integration",
"Service-Oriented Architecture (SOA)",
"Data Integrator",
"Data Integration",
"GoldenGate",
"WebLogic",
"GraalVM",
"Visual Builder Studio",
"Logging",
"Logging Analytics",
"Monitoring",
"Human Resources",
"Talent Management",
"Talent Management",
"Talent Management",
"Talent Management",
"Notifications",
"Email Delivery",
"Resource Manager",
"Cloud Shell",
"Container Engine for Kubernetes (OKE)",
"Container Registry (OCIR)",
"Functions (serverless)",
"API Management",
"Events Service",
"Streaming",
"Virtual Machines",
"Bare Metal",
"Talent Management",
"Talent Management",
"Workforce Management",
"Workforce Management",
"Workforce Management",
"Payroll",
"Payroll",
"Payroll",
"Payroll",
"Payroll",
"Virtual Machines and Bare Metal (GPU)",
"Functions",
"Financial Management",
"Procurement",
"Project Management",
"Risk Management and Compliance",
"Enterprise Performance Management",
"ERP Analytics",
"Supply Chain Planning",
"Inventory Management",
"Manufacturing",
"Maintenance",
"Payroll",
"Sales Automation",
"Sales Automation",
"Sales Automation",
"Sales Automation",
"Sales Automation",
"Commerce",
"Commerce",
"B2B Service",
"B2B Service",







"Advanced Security",
"Data Masking and Subsetting",
"Database Vault",
"Label Security",
"Access Management",
"Identity Governance",
"Directory Services",
"Data Integrator",
"GoldenGate",
"Financial Management",
"Financial Management",













"Financial Management",
"Financial Management",
"Financial Management",
"Procurement",
"Procurement",
"Project Management",
"Project Management",
"Risk Management and Compliance",
"Risk Management and Compliance",
"Enterprise Performance Management",







"B2B Service",
"B2B Service",
"B2C Service",
"B2C Service",
"B2C Service",
"B2C Service",
"B2B Marketing",
"B2B Marketing",














"Merchandising",
"Planning",
"Supply Chain",
"Brand Compliance Management",
"Hardware",
"Asset and Field Work Management",
"Customer Operations and Engagement",
"Opower",
"Advanced Metering",
"Network Management",
"Live Energy Connect",
"Audiences",














"OnRamp",
"Contextual Intelligence",
"Moat Analytics",
"Moat Outcomes",
"Moat Reach",
"WebCenter Content",
"WebCenter Portal",
"WebCenter Sites",
"VM Virtual Box",
"Audit Vault and Database Firewall",
"Database Security Assessment Tool",
"Key Vault",
"B2B Service",
"B2B Service",
"B2C Service",
"B2C Service",
"B2C Service",
"B2C Service",
"B2B Marketing",
"B2B Marketing",
"B2B Marketing",
"B2B Marketing",
"Order Management",
"Procurement",
"Logistics",
"Product Lifecycle Management",
"Blockchain",
"Internet of Things (IoT)",
"Human Resources",
"Talent Management",
"Workforce Management",
"Payroll",
"HCM Analytics",
"Sales Automation",
"B2B Marketing",
"B2B Marketing",
"B2B Marketing",
"B2C Marketing",
"B2C Marketing",
"B2C Marketing",
"B2C Marketing",
"B2C Marketing",
"B2C Marketing",
"B2C Marketing",
"Merchandising",
"Planning",
"Supply Chain",
"Brand Compliance Management",
"Hardware",
"Asset and Field Work Management",
"Customer Operations and Engagement",
"Opower",
"Advanced Metering",
"Network Management",
"Live Energy Connect",
"Audiences",
"OnRamp",
"Contextual Intelligence",
"Moat Analytics",
"Moat Outcomes",
"Moat Reach",
"WebCenter Content",
"WebCenter Portal",
"WebCenter Sites",
"VM Virtual Box",
"Audit Vault and Database Firewall",
"Database Security Assessment Tool",
"Key Vault"
}
l4_products = {
"Enterprise Data Management",
"Supply Planning",
"Sales and Operations Planning",
"Supply Chain Collaboration",
"Demand Management",
"Order Management",
"Service Contracts",
"Procurement",
"Self-Service Procurement",
"Logistics Network Modeling",
"Warehouse Management",
"Transportation Management",
"Transportation Operational Planning",
"Fleet Management",
"Global Trade Management",
"Intelligent Track and Trace",
"Blockchain Platform",
"IoT Intelligent Applications",
"Mobile Worker for IoT Intelligent Applications",
"IoT 3D Digital Twin",
"Human Resources (Core)",
"Human Resources Help Desk",
"Work Life",
"Benefits",
"Workforce Modeling and Predictions",
"Strategic Workforce Planning",

"Advanced HCM Controls",
"Recruiting",
"Onboarding",
"Performance Management",
"Compensation",
"Learning",
"Succession Planning",
"Absence Management",
"Time and Labor",
"Workforce Health and Safety",
"United States Payroll",
"Canada Payroll",
"United Kingdom Payroll",
"China Payroll",
"Mexico Payroll",
"Middle East Payroll",
"Sales Force Automation",
"Sales Planning",
"Sales Performance Management",
"Customer Data Management",
"DataFox Data Management",
"B2B Commerce",
"B2C Commerce",
"Service Center",
"Digital Customer Service",
"Financials",
"Self-Service Financials",
"Configure, Price, Quote",
"Accounting Hub",
"Subscription Management",
"Procurement",
"Self-Service Procurement",
"Project Management",
"Self-Service Project Management",
"Risk Management",
"Financial Reporting Compliance",
"Enterprise Performance Management",
"Knowledge Management",
"Intelligent Advisor",
"Service Center",
"Digital Customer Service",
"Knowledge Management",
"Intelligent Advisor",
"Eloqua Marketing Automation",
"DataFox Data Management",
"Knowledge Management",
"Intelligent Advisor",
"Service Center",
"Digital Customer Service",
"Knowledge Management",
"Intelligent Advisor",
"Eloqua Marketing Automation",
"DataFox Data Management",
"CrowdTwist Loyalty and Engagement",
"Content Management",
"Infinity Behavioral Intelligence",
"Maxymiser Testing and Optimization",
"Unity Customer Data Platform",
"Responsys Campaign Management",
"BlueKai Data Management Platform",
"CrowdTwist Loyalty and Engagement",
"Audience Segmentation",
"Content Management",
"Infinity Behavioral Intelligence",
"Maxymiser Testing and Optimization"
}

# oce_products = list(l3_products.union(l4_products))
oce_products = list(products_name)
